[package]
name = "hello-d2d"
version = "0.1.0"
edition = "2021"


[dependencies.windows]
version = "0.42"

features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader"
]